name: github-action
run-name: ${{ github.actor }} is out building GitHub Actions

on:
  push:
    # Pattern matched against refs/tags
    tags:        
      - '**' 

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build Maven Projects
        run: |
          mvn clean package -f ./interest/pom.xml
          mvn clean package -f ./consultation/pom.xml
          mvn clean package -f ./project/pom.xml
          mvn clean package -f ./BoundedContext262/pom.xml

      - name: Docker Build and push for Interest
        uses: docker/build-push-action@v4
        with:
          context: ./interest
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/interest:latest
            ghcr.io/${{ github.repository }}/interest:${{ github.ref_name }}
            
      - name: Docker Build and push for Consultation
        uses: docker/build-push-action@v4
        with:
          context: ./consultation
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/consultation:latest
            ghcr.io/${{ github.repository }}/consultation:${{ github.ref_name }}
            
      - name: Docker Build and push for Project
        uses: docker/build-push-action@v4
        with:
          context: ./project
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/project:latest
            ghcr.io/${{ github.repository }}/project:${{ github.ref_name }}
            
      - name: Docker Build and push for BoundedContext262
        uses: docker/build-push-action@v4
        with:
          context: ./BoundedContext262
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/boundedcontext262:latest
            ghcr.io/${{ github.repository }}/boundedcontext262:${{ github.ref_name }}
            
