apiVersion: apps/v1
kind: Deployment
metadata:
  name: BoundedContext262
  labels:
    app: BoundedContext262
spec:
  replicas: 1
  selector:
    matchLabels:
      app: BoundedContext262
  template:
    metadata:
      labels:
        app: BoundedContext262
    spec:
      containers:
        - name: BoundedContext262
          image: "username/BoundedContext262:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
